version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_URL=http://localhost:9090
  server:
    build: server
    image: server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_DB=shareit
      - POSTGRES_USER=user1234
      - POSTGRES_PASSWORD=shareit
  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=user1234
      - POSTGRES_PASSWORD=shareit
