drop table if exists users, requests, items, bookings, comments;
create table if not exists users
(
    id              bigint not null primary key,
    name            varchar(255) not null,
    email           varchar(255) not null unique
);

create table if not exists requests
(
    id              bigint not null generated by default as identity primary key,
    description     text not null,
    requestor_id    bigint references users (id) on delete cascade
);

create table if not exists items
(
    id              bigint not null generated by default as identity primary key,
    name            varchar(255) not null,
    description     text not null,
    is_available    boolean not null,
    owner_id        bigint references users (id) on delete cascade,
    request_id      bigint default null references requests (id) on delete set null
);

create table if not exists bookings
(
    id              bigint not null generated by default as identity primary key,
    date_start      timestamp without time zone not null,
    date_end        timestamp without time zone not null,
    status          varchar not null,
    item_id         bigint references items (id) on delete cascade,
    booker_id       bigint references users (id) on delete cascade
);

create table if not exists comments
(
    id              bigint not null generated by default as identity primary key,
    comment         text not null,
    item_id         bigint references items (id) on delete cascade,
    author_id       bigint references items (id) on delete cascade,
    created         timestamp without time zone not null
);